Tracker:AddLocations("locations/Basement.json")
Tracker:AddLocations("locations/Gym Class.json")
Tracker:AddLocations("locations/Intro.json")
Tracker:AddLocations("locations/Master Class.json")
Tracker:AddLocations("locations/Playground.json")
Tracker:AddLocations("locations/Roccos Arcade.json")
Tracker:AddLocations("locations/School.json")
Tracker:AddLocations("locations/Wholesale.json")
Tracker:AddLocations("locations/Overworld.json")
